# Generated by Django 3.0.5 on 2020-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200818_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('police', 'police'), ('owner', 'owner')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
