# Generated by Django 3.0.5 on 2020-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200818_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('police', 'police'), ('owner', 'owner')], default='driver', max_length=10),
        ),
    ]
