# Generated by Django 3.0.5 on 2020-08-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200818_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
