# Generated by Django 3.0.5 on 2020-08-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicel_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('2-wheelers', '2-wheelers'), ('4-wheelers', '4-wheelers'), ('bicycle', 'bicycle')], help_text='select your vehicle type', max_length=10)),
                ('entry_time', models.DateTimeField(editable=False)),
                ('end_time', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
            },
        ),
    ]
