# Generated by Django 3.0.3 on 2020-08-31 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_type', models.CharField(choices=[('owner', 'owner'), ('policeman', 'policeman'), ('driver', 'driver')], max_length=10)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_type', models.CharField(choices=[('self', 'self'), ('wallet', 'wallet')], max_length=10)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicalFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'car'), ('bike', 'bike'), ('cycle', 'cycle')], max_length=10)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parking',
            name='logs',
        ),
        migrations.AddField(
            model_name='parking',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='exit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='parking_type',
            field=models.CharField(choices=[('self', 'self'), ('wallet', 'wallet')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='vehicle_color',
            field=models.CharField(default=555, max_length=100),
            preserve_default=False,
        ),
    ]
